services:
  - type: web
    name: ecommerce-churn-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements-simple.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/database.db
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
