services:
  - type: web
    name: ecommerce-churn-backend
    env: python
    plan: free
    rootDir: backend
    pythonVersion: 3.11.0
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/database.db
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
